### ISSUE TITLE
No HTTPS

### ISSUE THREAD

**Issue by yashghelani** [thedaviddias/Front-End-Checklist#108]
Under the security section, the [site](http://frontendchecklist.com) mentions the use of HTTPS yet the [site](http://frontendchecklist.com) itself doesn't use it

**Comment by thedaviddias** [comment]
Hi @yashghelani, thanks for your comment, but It would be better to ask instead of giving a negative comment.

As you may not know, Github doesn't allow using HTTPS when a custom domain is used through Github Pages.

![screen shot 2017-10-27 at 23 55 13](https://user-images.githubusercontent.com/237229/32122692-49d38bd6-bb72-11e7-98ac-45a0088dc2de.jpg)

In the next days, a new version will come out, probably with HTTPS enable. I really hope to receive more constructive comments from you 😉

**Comment by yashghelani** [comment]
Hey. I didn't mean to point out this issue in a negative way. Sorry about my tone. I didn't know this site was hosted on GH Pages (My fault here. I should have noticed the CNAME file in the repo). Hope to seeing HTTPS soon :)

**Comment by thedaviddias** [comment]
You are completely forgiven 😅. You'll tell me next week what do you thing about the new app!
