### ISSUE TITLE
"Portuguese" language should use Portuguese flag

### ISSUE THREAD

**Issue by esr360** [thedaviddias/Front-End-Checklist#120]
The "Portuguese" port is showing the Brazilian flag, I think it would make more sense to show the Portuguese flag.

**Comment by thedaviddias** [comment]
Hi @esr360,

I don't understand the "more sense"...

I put the flag knowing that who made the traduction is Brazilian. You can find everywhere distinction between "Portuguese" from "Portugal" and "[Portuguese](https://en.wikipedia.org/wiki/Brazilian_Portuguese)" from "Brazil" because event Portuguese from Brazil is based on which coming from Portugal, it exists a lot of different words and expressions :)

**Comment by jcezarms** [comment]
I am the one who translated it, and like @thedaviddias said, it's in Brazillian Portuguese.
I reckon there are some (_many_) changes one should make in order to make it Portuguese as in Portugal's official idiom, and would love to help in such a fork.

**Comment by esr360** [comment]
Makes sense! I mistakenly thought it was more along the lines of seeing something like: 🇺🇸English 😅

**Comment by thedaviddias** [comment]
No problem 😀.

**Comment by Jayntlatleng** [comment]
Hey guys adding on your conversation on the guy who translate Portuguese, why don't you have an app that translates Portuguese than you being the one who translate it
