### ISSUE TITLE
"Sass is preferred"

### ISSUE THREAD

**Issue by matt-bailey** [thedaviddias/Front-End-Checklist#140]
That's a big assumption to make... Sass is preferred by whom? By you, by me, by the Overlords of Planet CSS?

It might be more correct to say Sass is (probably) the most popular CSS preprocessor, but many people choose to use (or are forced to use due to framework restrictions) LESS or Stylus for example.

Personally I don't care which preprocessor is used, as long as you use one. The end result is the same - they make my life easier :)

And what about people who prefer CSS post-processors...

**Comment by juanpagfe** [comment]
Hi. I support this idea because, as the `README.md` says 

> ...is an exhaustive list of all elements you need to have / to test before launching your site / HTML page to production...

We could add some notes about recommended technologies, but I don't think the use of a CSS preprocessor is a to-have thing for a website.

**Comment by MrSunshyne** [comment]
There was a similar discussion on a closed issue here : #92 

Right now the checklist says "Your page is using a CSS preprocessor [low] (Sass is preferred)"

Recommend changing the sentence to "The _project_ is using a CSS preprocessor or postprocessor. [low] (SASS is recommended as preprocessor)"

1. The page(in browser) cannot use a preprocessor technically, so change wording to say it's in the project. (Should I send a PR @thedaviddias ?)
2. Keep the [low] flag instead of removing this completely, simply because these tools make writing css much more enjoyable, and maintainable. Definitely recommended to be in a developer's checklist for sanity purposes.
3. Agree on recommending SASS explicitly. Like david mentioned, Bootstrap 4 moving from less to sass speaks for itself.

**Comment by matt-bailey** [comment]
I like the tweaks that @MrSunshyne suggests.

I'm still a little uncomfortable though saying that "Sass is recommended" without any mention at all that using Less or Stylus are equally valid and good options.

Either way, I understand why you're saying it. Do what you feel is best, it's your project :)

**Comment by dashed** [comment]
Why not compromise with: 

> Your page is using a CSS preprocessor (e.g. Sass).

or 
> Your page is using a CSS preprocessor (for example: Sass).

**Comment by sebastienrocks** [comment]
I agree with @MrSunshyne on the phrasing:

"Your page is using a CSS preprocessor"

to

"Your project is using a CSS preprocessor"

**Comment by thedaviddias** [comment]
@sebastienrocks @dashed @MrSunshyne I removed "sass is prefered" and change "your page" to "your project". Tell me if it's fine for you now.

**Comment by sebastienrocks** [comment]
@thedaviddias this works for me personally, although I do think an e.g. would be useful to newer developers (in the case they've never heard of a preprocessor), however it works in the current state.

**Comment by thedaviddias** [comment]
@sebastienrocks Better now?

**Comment by sebastienrocks** [comment]
@thedaviddias Looks a lot better to me :)

**Comment by thedaviddias** [comment]
@matt-bailey Can you close the ticket or I do?

**Comment by matt-bailey** [comment]
Looks good! I'll close the ticket :)
