### ISSUE TITLE
how to run on Local Machine?

### ISSUE THREAD

**Issue by singhvaibhavram** [thedaviddias/Front-End-Checklist#190]
I am using ubuntu. What are the dependencies to install and can someone please update the readme page so that it states that how do we run this code on local machine. I am new here.

**Comment by jackwilsdon** [comment]
It looks like [README_APP.md](https://github.com/thedaviddias/Front-End-Checklist/blob/master/README_APP.md) needs updating with the correct steps.

Try this to start a development server (you'll need NodeJS installed);
```
npm install
npm run start
```

And to build it;
```
npm build
```

**Comment by thedaviddias** [comment]
Sorry @singhvaibhavram, I had some delay to finish the README_APP. It'll be updated in the next days with everything explained.

Thanks @jackwilsdon for the support. If you have any issue, you can use ```gulp dev``` instead of ```npm run start```.

It seems to have an issue with the app.bundle.js file. If it's the case, launch ```npm build``` one time and everything will work properly after.

Sorry again for the delay of these corrections / writing.

**Comment by sugus25** [comment]
How to install on my device 



Than you

**Comment by msuri44** [comment]
What do you think about dockerize this solution to run the solution faster and easier locally?

**Comment by thedaviddias** [comment]
@msuri44 indeed that may help... even we don't have a "real" application.
