### ISSUE TITLE
I disagree with certain points of the favicon advice

### ISSUE THREAD

**Issue by chris-morgan** [thedaviddias/Front-End-Checklist#20]
> If you have only a favicon.ico, put it at the root of your site. Normally you won’t need to use any markup. However, it’s still good practice to link to it using the example below.

Why? It’s completely unnecessary, getting you absolutely nothing.

> Today, PNG format is recommended over .ico format (dimensions: 32x32px)

I strongly disagree with this; 16×16 and 32×32 are distinct design targets, and there is value in tweaking the design for the different sizes, mostly for optimal clarity at 16×16. You can use multiple `<link rel=icon>` elements with varying `sizes` attributes, but there are compatibility issues with doing that; it’s safest to have the .ico version include both 16×16 and 32×32, and then if you have more sizes, add them all to the document head.

**Comment by thedaviddias** [comment]
Hi @chris-morgan, maybe for the example, I need to add a subfolder like ``<link rel="icon" type="image/x-icon" href="https://example.com/img/favicon.ico" />``. Indeed, pointing to the root is not necessary.

I hesitated to put *PNG as recommended* but I found on canisue.com:
* While all browsers support the .ico format, the PNG format can be preferable (I provided the link on the checklist)

And on CSS-Tricks:

* Altough all desktop browsers support favicon.ico, this file is mostly deprecated. Yes, you can still rely on this file and it will work as expected. But seriously, it's an old deprecated format. It is not used anywhere else in web technology. PNG is much more consistent.

It's why it seems to be better to use PNG instead of .ICO. What do you think?

**Comment by volosovich** [comment]
Hey!
Your site http://frontendchecklist.com doesn't have favicon :)

**Comment by thedaviddias** [comment]
Ahahaha @volosovich! Indeed but it's because it is generated by [Github Pages](https://pages.github.com/) and they don't give the possibilité to add a Favicon.

**Comment by volosovich** [comment]
http://yeoman.io/
https://github.com/yeoman/yeoman.github.io/tree/source/app
has favicon :)

**Comment by thedaviddias** [comment]
Yes @volosovich, but it's because they are using [Jekyll](https://github.com/jekyll/jekyll) custom (generator-jekyllrb), it's something I'll probably use instead of default template by Github soon. 😉

**Comment by thedaviddias** [comment]
@chris-morgan what do you think, regarding my previous response?

**Comment by andydavies** [comment]
There are other HTTP clients (bookmarking services etc) that will look for favicon.ico in the root.

And if there's not one there they'll get a 404, and if you serve a custom error page then they'll get that instead (seen sites where they were serving a 40KB error page rather than a tiny icon)

So I recommend to clients they have a favicon.ico even if they don't link to it in the page

It's worth mining server logs to see what other icons are being requested for the same reason

**Comment by thedaviddias** [comment]
Thanks @andydavies for your feedback. I'll change the rule to take that into consideration. Don't hesitate to do a PR.

**Comment by thedaviddias** [comment]
Hi @chris-morgan, @andydavies, regarding that page https://en.wikipedia.org/wiki/Favicon it seems to put the favicon at the root, is not the best option compared to ```<link rel="shortcut icon"
 href="http://example.com/myicon.ico">``` for example. What do you think? What you propose as an alternative to the current text?

**Comment by chris-morgan** [comment]
Iff you have no other `rel=icon` links, then `<link rel="shortcut icon" href=/favicon.ico>` is completely superfluous.
