### ISSUE TITLE
The Arabic Language

### ISSUE THREAD

**Issue by noamangg** [thedaviddias/Front-End-Checklist#504]
Hey There is there a chance to add the Arabic language in this great art ?, I would be glad to do it

**Comment by KetanParmar02** [comment]
Hey, @noamangg I am interested in this issue..
please assign to me this issue.

**Comment by KetanParmar02** [comment]
So, what should I do next please suggest me?

**Comment by alfill** [comment]
Hello @noamangg, @KetanParmar02  - the author replied earlier in [similar issue](https://github.com/thedaviddias/Front-End-Performance-Checklist/issues/5) - just add a [link](https://github.com/thedaviddias/Front-End-Checklist/pull/452/files) to your published work.

If you want to see the translation published in html - you need switch to the gh-pages branch where the index.html file is stored, then setup Github-Pages and domain name for your own repo.

Although it would have been better to store translations in the common repository, but it was not foreseen beforehand because it requires more time and attention which few people have.
