### ISSUE TITLE
Preprocessor

### ISSUE THREAD

**Issue by webetcaetera** [thedaviddias/Front-End-Checklist#92]
In the CSS part, perhaps the use of a preprocessor can be upgraded to LOW or even removed? 
A preprocessor is just an option, but not a guarantee of quality. 
If used, ok for the SASS recommendation, especially for beginners.

**Comment by MrSunshyne** [comment]
Agree on the mention of preprocessor. I would even recommend not using preprocessors at all if possible. But rather use css custom properties(as variables)

If mixins are required in the project, then unfortunately you must use a preprocessor, since the `@apply` rule is not likely to be implemented natively anytime soon.. :(

Recommend : `low`

**Comment by thedaviddias** [comment]
Thanks for sharing your POV. I'll change and put it as "low" recommendation.

**Comment by thedaviddias** [comment]
@webetcaetera, if you agree please close the ticket. Thanks and don't hesitate if you find something else that need corrections.

**Comment by webetcaetera** [comment]
Thanks :)

**Comment by benface** [comment]
I would be for removing the preprocessor recommendation altogether, as I believe it's the only point in the whole list that is 100% about tooling and not about the final result (that the browser sees).
